/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ACCESS_CONTROL_MESSAGE_PB_H_INCLUDED
#define PB_ACCESS_CONTROL_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _access_control_StatusType {
    access_control_StatusType_STATUS_TYPE_UNSPECIFIED = 0, /* 未指定 */
    access_control_StatusType_STATUS_TYPE_OK = 1, /* 成功 */
    access_control_StatusType_STATUS_TYPE_AUTH_FAILED = 2, /* 驗證失敗 */
    access_control_StatusType_STATUS_TYPE_TIMEOUT = 3, /* 超時 */
    access_control_StatusType_STATUS_TYPE_CANCELLED = 4 /* 取消或拒絕 */
} access_control_StatusType;

/* Struct definitions */
typedef struct _access_control_PasswordInputEvent {
    char password[16];
} access_control_PasswordInputEvent;

typedef PB_BYTES_ARRAY_T(10) access_control_RfidScannedEvent_uid_t;
typedef struct _access_control_RfidScannedEvent {
    access_control_RfidScannedEvent_uid_t uid;
} access_control_RfidScannedEvent;

typedef struct _access_control_IrTriggeredEvent {
    char dummy_field;
} access_control_IrTriggeredEvent;

typedef struct _access_control_FaceRegistrationEvent {
    char dummy_field;
} access_control_FaceRegistrationEvent;

typedef struct _access_control_RfidRegistrationEvent {
    char dummy_field;
} access_control_RfidRegistrationEvent;

typedef struct _access_control_SystemResetEvent {
    char dummy_field;
} access_control_SystemResetEvent;

typedef struct _access_control_UnlockCommand {
    char dummy_field;
} access_control_UnlockCommand;

typedef struct _access_control_ControlRgbLedCommand {
    bool red;
    bool green;
    bool blue;
} access_control_ControlRgbLedCommand;

typedef struct _access_control_ActionResponse {
    access_control_StatusType status;
    char message[32];
} access_control_ActionResponse;

typedef struct _access_control_PiMessage {
    pb_size_t which_body;
    union {
        access_control_UnlockCommand unlock;
        access_control_ControlRgbLedCommand control_rgb_led;
        access_control_ActionResponse action_response;
    } body;
} access_control_PiMessage;

typedef struct _access_control_CommandResponse {
    access_control_StatusType status;
} access_control_CommandResponse;

typedef struct _access_control_Stm32Message {
    pb_size_t which_body;
    union {
        access_control_PasswordInputEvent password_input;
        access_control_RfidScannedEvent rfid_scanned;
        access_control_IrTriggeredEvent ir_triggered;
        access_control_FaceRegistrationEvent face_registration;
        access_control_RfidRegistrationEvent rfid_registration;
        access_control_SystemResetEvent system_reset;
        access_control_CommandResponse command_response;
    } body;
} access_control_Stm32Message;

typedef struct _access_control_SmartLockPacket {
    uint32_t sequence;
    pb_size_t which_packet_body;
    union {
        access_control_Stm32Message stm32_message;
        access_control_PiMessage pi_message;
    } packet_body;
} access_control_SmartLockPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _access_control_StatusType_MIN access_control_StatusType_STATUS_TYPE_UNSPECIFIED
#define _access_control_StatusType_MAX access_control_StatusType_STATUS_TYPE_CANCELLED
#define _access_control_StatusType_ARRAYSIZE ((access_control_StatusType)(access_control_StatusType_STATUS_TYPE_CANCELLED+1))












#define access_control_ActionResponse_status_ENUMTYPE access_control_StatusType

#define access_control_CommandResponse_status_ENUMTYPE access_control_StatusType


/* Initializer values for message structs */
#define access_control_SmartLockPacket_init_default {0, 0, {access_control_Stm32Message_init_default}}
#define access_control_Stm32Message_init_default {0, {access_control_PasswordInputEvent_init_default}}
#define access_control_PiMessage_init_default    {0, {access_control_UnlockCommand_init_default}}
#define access_control_PasswordInputEvent_init_default {""}
#define access_control_RfidScannedEvent_init_default {{0, {0}}}
#define access_control_IrTriggeredEvent_init_default {0}
#define access_control_FaceRegistrationEvent_init_default {0}
#define access_control_RfidRegistrationEvent_init_default {0}
#define access_control_SystemResetEvent_init_default {0}
#define access_control_UnlockCommand_init_default {0}
#define access_control_ControlRgbLedCommand_init_default {0, 0, 0}
#define access_control_ActionResponse_init_default {_access_control_StatusType_MIN, ""}
#define access_control_CommandResponse_init_default {_access_control_StatusType_MIN}
#define access_control_SmartLockPacket_init_zero {0, 0, {access_control_Stm32Message_init_zero}}
#define access_control_Stm32Message_init_zero    {0, {access_control_PasswordInputEvent_init_zero}}
#define access_control_PiMessage_init_zero       {0, {access_control_UnlockCommand_init_zero}}
#define access_control_PasswordInputEvent_init_zero {""}
#define access_control_RfidScannedEvent_init_zero {{0, {0}}}
#define access_control_IrTriggeredEvent_init_zero {0}
#define access_control_FaceRegistrationEvent_init_zero {0}
#define access_control_RfidRegistrationEvent_init_zero {0}
#define access_control_SystemResetEvent_init_zero {0}
#define access_control_UnlockCommand_init_zero   {0}
#define access_control_ControlRgbLedCommand_init_zero {0, 0, 0}
#define access_control_ActionResponse_init_zero  {_access_control_StatusType_MIN, ""}
#define access_control_CommandResponse_init_zero {_access_control_StatusType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define access_control_PasswordInputEvent_password_tag 1
#define access_control_RfidScannedEvent_uid_tag  1
#define access_control_ControlRgbLedCommand_red_tag 1
#define access_control_ControlRgbLedCommand_green_tag 2
#define access_control_ControlRgbLedCommand_blue_tag 3
#define access_control_ActionResponse_status_tag 1
#define access_control_ActionResponse_message_tag 2
#define access_control_PiMessage_unlock_tag      1
#define access_control_PiMessage_control_rgb_led_tag 2
#define access_control_PiMessage_action_response_tag 3
#define access_control_CommandResponse_status_tag 1
#define access_control_Stm32Message_password_input_tag 1
#define access_control_Stm32Message_rfid_scanned_tag 2
#define access_control_Stm32Message_ir_triggered_tag 3
#define access_control_Stm32Message_face_registration_tag 4
#define access_control_Stm32Message_rfid_registration_tag 5
#define access_control_Stm32Message_system_reset_tag 6
#define access_control_Stm32Message_command_response_tag 7
#define access_control_SmartLockPacket_sequence_tag 1
#define access_control_SmartLockPacket_stm32_message_tag 2
#define access_control_SmartLockPacket_pi_message_tag 3

/* Struct field encoding specification for nanopb */
#define access_control_SmartLockPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sequence,          1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (packet_body,stm32_message,packet_body.stm32_message),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (packet_body,pi_message,packet_body.pi_message),   3)
#define access_control_SmartLockPacket_CALLBACK NULL
#define access_control_SmartLockPacket_DEFAULT NULL
#define access_control_SmartLockPacket_packet_body_stm32_message_MSGTYPE access_control_Stm32Message
#define access_control_SmartLockPacket_packet_body_pi_message_MSGTYPE access_control_PiMessage

#define access_control_Stm32Message_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,password_input,body.password_input),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,rfid_scanned,body.rfid_scanned),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,ir_triggered,body.ir_triggered),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,face_registration,body.face_registration),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,rfid_registration,body.rfid_registration),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,system_reset,body.system_reset),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,command_response,body.command_response),   7)
#define access_control_Stm32Message_CALLBACK NULL
#define access_control_Stm32Message_DEFAULT NULL
#define access_control_Stm32Message_body_password_input_MSGTYPE access_control_PasswordInputEvent
#define access_control_Stm32Message_body_rfid_scanned_MSGTYPE access_control_RfidScannedEvent
#define access_control_Stm32Message_body_ir_triggered_MSGTYPE access_control_IrTriggeredEvent
#define access_control_Stm32Message_body_face_registration_MSGTYPE access_control_FaceRegistrationEvent
#define access_control_Stm32Message_body_rfid_registration_MSGTYPE access_control_RfidRegistrationEvent
#define access_control_Stm32Message_body_system_reset_MSGTYPE access_control_SystemResetEvent
#define access_control_Stm32Message_body_command_response_MSGTYPE access_control_CommandResponse

#define access_control_PiMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,unlock,body.unlock),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,control_rgb_led,body.control_rgb_led),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,action_response,body.action_response),   3)
#define access_control_PiMessage_CALLBACK NULL
#define access_control_PiMessage_DEFAULT NULL
#define access_control_PiMessage_body_unlock_MSGTYPE access_control_UnlockCommand
#define access_control_PiMessage_body_control_rgb_led_MSGTYPE access_control_ControlRgbLedCommand
#define access_control_PiMessage_body_action_response_MSGTYPE access_control_ActionResponse

#define access_control_PasswordInputEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   password,          1)
#define access_control_PasswordInputEvent_CALLBACK NULL
#define access_control_PasswordInputEvent_DEFAULT NULL

#define access_control_RfidScannedEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    uid,               1)
#define access_control_RfidScannedEvent_CALLBACK NULL
#define access_control_RfidScannedEvent_DEFAULT NULL

#define access_control_IrTriggeredEvent_FIELDLIST(X, a) \

#define access_control_IrTriggeredEvent_CALLBACK NULL
#define access_control_IrTriggeredEvent_DEFAULT NULL

#define access_control_FaceRegistrationEvent_FIELDLIST(X, a) \

#define access_control_FaceRegistrationEvent_CALLBACK NULL
#define access_control_FaceRegistrationEvent_DEFAULT NULL

#define access_control_RfidRegistrationEvent_FIELDLIST(X, a) \

#define access_control_RfidRegistrationEvent_CALLBACK NULL
#define access_control_RfidRegistrationEvent_DEFAULT NULL

#define access_control_SystemResetEvent_FIELDLIST(X, a) \

#define access_control_SystemResetEvent_CALLBACK NULL
#define access_control_SystemResetEvent_DEFAULT NULL

#define access_control_UnlockCommand_FIELDLIST(X, a) \

#define access_control_UnlockCommand_CALLBACK NULL
#define access_control_UnlockCommand_DEFAULT NULL

#define access_control_ControlRgbLedCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     red,               1) \
X(a, STATIC,   SINGULAR, BOOL,     green,             2) \
X(a, STATIC,   SINGULAR, BOOL,     blue,              3)
#define access_control_ControlRgbLedCommand_CALLBACK NULL
#define access_control_ControlRgbLedCommand_DEFAULT NULL

#define access_control_ActionResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1) \
X(a, STATIC,   SINGULAR, STRING,   message,           2)
#define access_control_ActionResponse_CALLBACK NULL
#define access_control_ActionResponse_DEFAULT NULL

#define access_control_CommandResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1)
#define access_control_CommandResponse_CALLBACK NULL
#define access_control_CommandResponse_DEFAULT NULL

extern const pb_msgdesc_t access_control_SmartLockPacket_msg;
extern const pb_msgdesc_t access_control_Stm32Message_msg;
extern const pb_msgdesc_t access_control_PiMessage_msg;
extern const pb_msgdesc_t access_control_PasswordInputEvent_msg;
extern const pb_msgdesc_t access_control_RfidScannedEvent_msg;
extern const pb_msgdesc_t access_control_IrTriggeredEvent_msg;
extern const pb_msgdesc_t access_control_FaceRegistrationEvent_msg;
extern const pb_msgdesc_t access_control_RfidRegistrationEvent_msg;
extern const pb_msgdesc_t access_control_SystemResetEvent_msg;
extern const pb_msgdesc_t access_control_UnlockCommand_msg;
extern const pb_msgdesc_t access_control_ControlRgbLedCommand_msg;
extern const pb_msgdesc_t access_control_ActionResponse_msg;
extern const pb_msgdesc_t access_control_CommandResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define access_control_SmartLockPacket_fields &access_control_SmartLockPacket_msg
#define access_control_Stm32Message_fields &access_control_Stm32Message_msg
#define access_control_PiMessage_fields &access_control_PiMessage_msg
#define access_control_PasswordInputEvent_fields &access_control_PasswordInputEvent_msg
#define access_control_RfidScannedEvent_fields &access_control_RfidScannedEvent_msg
#define access_control_IrTriggeredEvent_fields &access_control_IrTriggeredEvent_msg
#define access_control_FaceRegistrationEvent_fields &access_control_FaceRegistrationEvent_msg
#define access_control_RfidRegistrationEvent_fields &access_control_RfidRegistrationEvent_msg
#define access_control_SystemResetEvent_fields &access_control_SystemResetEvent_msg
#define access_control_UnlockCommand_fields &access_control_UnlockCommand_msg
#define access_control_ControlRgbLedCommand_fields &access_control_ControlRgbLedCommand_msg
#define access_control_ActionResponse_fields &access_control_ActionResponse_msg
#define access_control_CommandResponse_fields &access_control_CommandResponse_msg

/* Maximum encoded size of messages (where known) */
#define ACCESS_CONTROL_MESSAGE_PB_H_MAX_SIZE     access_control_SmartLockPacket_size
#define access_control_ActionResponse_size       35
#define access_control_CommandResponse_size      2
#define access_control_ControlRgbLedCommand_size 6
#define access_control_FaceRegistrationEvent_size 0
#define access_control_IrTriggeredEvent_size     0
#define access_control_PasswordInputEvent_size   17
#define access_control_PiMessage_size            37
#define access_control_RfidRegistrationEvent_size 0
#define access_control_RfidScannedEvent_size     12
#define access_control_SmartLockPacket_size      45
#define access_control_Stm32Message_size         19
#define access_control_SystemResetEvent_size     0
#define access_control_UnlockCommand_size        0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
